name: Notify website to sync

on:
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - 'readme.md'
      - 'docs/**'
      - 'assets/**'
      - 'images/**'
      - 'img/**'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.webp'
      - '**/*.mp4'
      - '**/*.pdf'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch to website repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WEBSITE_DISPATCH_TOKEN }}
          repository: euro-macromechanica-backtest/euro-macromechanica-backtest.github.io
          event-type: sync-readme
